coment:
  require_changes: true

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

# Don't calculate code coverage percentages on generated abigen files
# or our profiling code
ignore:
  - ethereum/swap_creator.go
  - ethereum/aggregator_v3_interface.go
  - ethereum/erc20_token.go
  - ethereum/ierc20.go
  - ethereum/block/ut_contract_test.go
  - cmd/swapd/profile.go
