[package]
name = "dleq-proof"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dleq-gen"
path = "src/generate.rs"

[[bin]]
name = "dleq-verify"
path = "src/verify.rs"

[dependencies]
farcaster_core = { git = "https://github.com/Lederstrumpf/farcaster-core", branch = "pub_hack", features = ["serde"] }
ecdsa_fun = { version = "0.6", default-features = false, features = ["all"] }
secp256kfun = { version = "0.6", default-features = false, features = ["std", "serde", "libsecp_compat"] }
curve25519-dalek = "3.0.2"
rand = { version = "0.8.4" }
hex = { version = "0.4.3" }
rand_core = "0.6"
